[project]
name = "gary"
version = "0.2.0"
description = "A Test Bed for MetaGraph-Powered LangGraph Agents "
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "networkx",
    "jsonschema",
]
